---
- name: "Load a variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- name: "Install requirements"
  package:
    name: "{{ requirements }}"
    state: "present"
  register: installed_packages
  until: installed_packages is success
  become: True
